Add controllers
MishaH9201/java-shareit pull request #3
Opened 2022-08-21 15:59 UTC by MishaH9201

2022-08-22 10:38 UTC, MishaH9201 commented
Тесты прошел в постмане https://github.com/yandex-praktikum/java-shareit/blob/add-controllers/postman/sprint.json

2022-08-23 11:30 UTC, Fleaman777 requested changes

2022-08-23 11:30 UTC, Fleaman777 commented on hs_err_pid17696.log
> +
.log файлы не нужны, 
возможно стоит добавить в гитигнор

2022-08-23 11:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public List<ItemDto> get(@RequestHeader("X-Sharer-User-Id") long userId) {
X-Sharer-User-Id можно вынести в константу, 
и исопльзовать ее в местах где используется X-Sharer-User-Id

2022-08-23 11:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                .collect(Collectors.toList());
этот стрим лучше бы перенсти в метод сервиса, аналагично в др местах

2022-08-23 11:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +                null
гуд практис, 
если в оюъект нужно проесетать много полей (больше 5), то лучше использовать билдер, а не конструктор

2022-08-23 11:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +                .orElse(null);
можно использовать метод orElseThrow.... 
код должен стать компактнее

2022-08-23 11:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                            && item.getAvailable() == true)
что бы стрим лучше читался, логику внутри filter можно вынести в отдельный метод

2022-08-28 09:27 UTC, merged